export const ERROR_CODES = {
  DB_TIMEOUT: "DB_TIMEOUT",
  QUEUE_OVERLOAD: "QUEUE_OVERLOAD",
  AUTH_EXPIRED: "AUTH_EXPIRED",
  INVALID_INPUT: "INVALID_INPUT",
  USERNAME_EXIST: "USERNAME_EXIST",
  EMAIL_EXIST: "EMAIL_EXIST",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_NOT_VERIFIED: "ACCOUNT_NOT_VERIFIED",
  INVALID_TOKEN: "INVALID_TOKEN",
  CONFLICT: "CONFLICT",
};
